version: '2'
services:
  web:
    build: ./.docker/services/node
    ports:
      - 3000:3000
    depends_on:
      - database
    environment:
      - DATABASE_HOST=database
    volumes:
      - .:/code
  database:
    build: ./.docker/services/mysql
    ports:
      - 33060:3306
