version: '2'
services:
  web:
    container_name: web-api
    build: ./.docker/services/node
    volumes:
      - .:/code
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - HOST=localhost
      - PORT_DATABASE=3306
      - USER_DATABASE=root
      - PASS_DATABASE=11111111
      - NAME_DATABASE=shoe
      - SESS_TIMELIFE=20000
      - SESS_NAME=begginer
      - SESS_SECRET=Hello
      - COOKIE_SECRET=Hello
      - SESS_TIMECHECK=500000
    depends_on:
      - mysql
    networks:
      - app-network
  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - '3306:3306'
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: 11111111
      MYSQL_DATABASE: shoe
      MYSQL_USER: thanhdat
      MYSQL_PASSWORD: 11111111
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
